SETTINGS_PRIORITY = 1

#PYFORMS_MODE = 'TERMINAL'

PYFORMS_STYLESHEET = 'style.css'
# PYFORMS_STYLESHEET_LINUX = 'style.css'
# PYFORMS_STYLESHEET_DARWIN = 'style.css.css'
PYFORMS_STYLESHEET_WINDOWS = 'style.css'
